application: cykelapp
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /cronjobs/.*
  script: cronjobs.cronjobs_app.application
  login: admin

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /css/(.*\.css)
  mime_type: text/css
  static_files: frontend/build/css/\1
  upload: frontend/build/css/(.*\.css)

- url: /js/(.*\.js)
  mime_type: text/javscript
  static_files: frontend/build/js/\1
  upload: frontend/build/js/(.*\.js)

- url: /(.*\.html)
  mime_type: text/html
  static_files: frontend/html/\1
  upload: frontend/html/(.*\.html)

- url: /api/.*
  script: webapp.cykel_app.application

- url: /
  static_files: frontend/html/index.html
  upload: frontend/html/index.html

libraries:
- name: webapp2
  version: "latest"

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)node_modules
