application: cykelapp
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /cronjobs/.*
  script: cronjobs.cronjobs_app.application
  login: admin

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /index.html
  static_files: frontend/index.html
  upload: frontend/index.html

- url: /js/.*
  static_dir: frontend/build/js

- url: /.*
  script: webapp.cykel_app.application

libraries:
- name: webapp2
  version: "latest"

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)node_modules
