application: cykelapp
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /cronjobs/.*
  script: cronjobs.cronjobs_app.application
  login: admin
- url: /.*
  script: webapp.cykel_app.application

libraries:
- name: webapp2
  version: "latest"
